"""
Auto-extracted module: header_mapping/aliases.py
"""

from __future__ import annotations

ALIAS_MAP: dict[str, str] = {
    "bldg no": "LocationID", "bldg no.": "LocationID", "building no": "LocationID",
    "building number": "LocationID", "location no": "LocationID", "loc no": "LocationID",
    "location number": "LocationID", "locnumber": "LocationID", "loc id": "LocationID",
    "location id": "LocationID", "loc": "LocationID", "bldg": "LocationID",
    "building id": "LocationID",
    "location name": "LocationName", "named insured": "LocationName",
    "location name named insured": "LocationName", "insured name": "LocationName",
    "site name": "LocationName", "locname": "LocName", "property name": "LocationName",
    "site": "LocationName",
    "street address": "Street", "street address combined": "Street",
    "full address": "Street", "address": "Street", "street": "Street",
    "addressnum": "Street", "streetaddress": "StreetAddress",
    "mailing address": "Street", "property address": "Street",
    "address line 1": "Street", "addr": "Street",
    "city": "City", "municipality": "City", "town": "City",
    "state": "Area", "state code": "Area", "province": "Area", "st": "Area",
    "statecode": "StateCode",
    "county": "SubArea", "sub area": "SubArea", "district": "SubArea",
    "parish": "SubArea", "borough": "SubArea",
    "zip": "PostalCode", "zip code": "PostalCode", "postal code": "PostalCode",
    "postcode": "PostalCode", "postal": "PostalCode", "zip4": "PostalCode",
    "country": "CountryISO", "country iso": "CountryISO",
    "countryiso": "CountryISO", "country code": "CountryISO",
    "countryisoa2": "CountryISOA2",
    "ind": "IND", "industry code": "IND", "rms ind": "IND",
    "of bldgs": "RiskCount", "number of buildings": "RiskCount",
    "no of bldgs": "RiskCount", "num bldgs": "RiskCount",
    "risk count": "RiskCount", "number of risks": "RiskCount",
    "bldg count": "RiskCount", "building count": "RiskCount",
    "of units": "NumUnits", "number of units": "NumUnits", "no of units": "NumUnits",
    "num units": "NumUnits", "units": "NumUnits",
    "real property value":               "BuildingValue",
    "real property value $":             "BuildingValue",
    "real property":                     "BuildingValue",
    "tenant improvements":               "BuildingValue",
    "tenant improvement":                "BuildingValue",
    "improvements and betterments":      "BuildingValue",
    "improvement and betterments":       "BuildingValue",
    "improvements betterments":          "BuildingValue",
    "ib":                                "BuildingValue",
    "building value":                    "BuildingValue",
    "building":                          "BuildingValue",
    "buildings":                         "BuildingValue",
    "structure":                         "BuildingValue",
    "structures":                        "BuildingValue",
    "plant":                             "BuildingValue",
    "other value": "OtherValue", "other value $": "OtherValue",
    "other value outdoor prop eqpt": "OtherValue",
    "outdoor property": "OtherValue", "avg inventory": "OtherValue",
    "inventory value": "OtherValue", "stock value": "OtherValue",
    "contents":                          "ContentsValue",
    "personal property value $": "BuildingValue",
    "contents value":                    "ContentsValue",
    "mse":                               "ContentsValue",
    "m&se":                              "ContentsValue",
    "m & se":                            "ContentsValue",
    "m&s&e":                             "ContentsValue",
    "m & s & e":                         "ContentsValue",
    "machinery supplies equipment":      "ContentsValue",
    "machinery supply equipment":        "ContentsValue",
    "machinery and supplies and equipment": "ContentsValue",
    "me":                                "ContentsValue",
    "me machinery equipment":            "ContentsValue",
    "machinery equipment":               "ContentsValue",
    "machinery and equipment":           "ContentsValue",
    "equipment":                         "ContentsValue",
    "furniture fixtures equipment":      "ContentsValue",
    "ffe":                               "ContentsValue",
    "ff&e":                              "ContentsValue",
    "bi rental income":             "TimeElementValue",
    "bi rental income $":           "TimeElementValue",
    "bi / rental income":           "TimeElementValue",
    "bi/rental income":             "TimeElementValue",
    "rental income value":          "TimeElementValue",
    "annual rental income":         "TimeElementValue",
    "gross rental income":          "TimeElementValue",
    "business interruption value":  "TimeElementValue",
    "business interruption $":      "TimeElementValue",
    "business income value":        "TimeElementValue",
    "loss of income":               "TimeElementValue",
    "loss of rents":                "TimeElementValue",
    "loss of rent":                 "TimeElementValue",
    "time element value":           "TimeElementValue",
    "te":                           "TimeElementValue",
    "te value":                     "TimeElementValue",
    "extra expense":                "TimeElementValue",
    "bi value":                     "BIValue",
    "bivalue":                      "BIValue",
    "business income":              "BIValue",
    "iso const": "ConstructionCode", "iso construction": "ConstructionCode",
    "construction type": "ConstructionCode", "construction description": "ConstructionCode",
    "construction code": "ConstructionCode", "const type": "ConstructionCode",
    "construction": "ConstructionCode", "classcode": "ClassCode",
    "class code": "ClassCode",
    "construction description provide further details on construction features": "ConstructionOther",
    "construction notes": "ConstructionOther", "construction details": "ConstructionOther",
    "construction comments": "ConstructionOther", "construction other": "ConstructionOther",
    "building construction notes": "ConstructionOther", "construction feature": "ConstructionOther",
    "occupancy description": "OccupancyCode", "occupancy": "OccupancyCode",
    "occupancy type": "OccupancyCode", "occ description": "OccupancyCode",
    "location description": "OccupancyCode", "occupancytype": "OccupancyType",
    "use type": "OccupancyCode", "property type": "OccupancyCode",
    "building use": "OccupancyCode",
    "orig year built": "YearBuilt", "year built": "YearBuilt",
    "original year built": "YearBuilt", "year of construction": "YearBuilt",
    "yr built": "YearBuilt", "year constructed": "YearBuilt",
    "yr bldg upgraded major exterior update mandatory if 25 yrs old": "YearBuilt",
    "of stories": "NumberOfStories", "no of stories": "NumberOfStories",
    "number of stories": "NumberOfStories", "stories": "NumberOfStories",
    "no of floors": "NumberOfStories", "floors": "NumberOfStories",
    "numstories": "NumStories", "number of floors": "NumberOfStories",
    "num stories": "NumberOfStories", "num floors": "NumberOfStories",
    "square footage": "GrossArea", "sq ft": "GrossArea", "gross area": "GrossArea",
    "floor area": "GrossArea", "total area": "GrossArea", "sqft": "GrossArea",
    "building area": "GrossArea", "total sq ft": "GrossArea",
    "year roof covering last replaced": "Roof Year Built",
    "year of last roof recovering": "Roof Year Built",
    "roof year": "Roof Year Built", "roof year built": "Roof Year Built",
    "year of last roof recovering if 25 yrs or older": "Roof Year Built",
    "roofcoveryear": "RoofCoverYear", "roof replacement year": "Roof Year Built",
    "percent sprinklered": "Sprinkler Availability",
    "sprinklered yn": "Sprinkler Availability",
    "sprinkler": "Sprinkler Availability",
    "sprinklertype": "SprinklerType", "sprinkler type": "SprinklerType",
    "sprinkler system": "Sprinkler Availability",
    "original ccy": "Currency", "currency": "Currency", "ccy": "Currency",
    "latitude": "Latitude", "lat": "Latitude",
    "longitude": "Longitude", "lon": "Longitude", "long": "Longitude",
}

